// components/FileUpload.tsx
import React, { useCallback, useState } from 'react';
import { UploadIcon, DocumentDuplicateIcon } from './icons';

interface FileUploadProps {
  onFileSelect: (file: File) => void;
  disabled?: boolean;
}

export const FileUpload: React.FC<FileUploadProps> = ({ onFileSelect, disabled }) => {
  const [isDragging, setIsDragging] = useState(false);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      onFileSelect(event.target.files[0]);
    }
  };

  const handleDrop = useCallback((event: React.DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragging(false);
    if (disabled) return;

    if (event.dataTransfer.files && event.dataTransfer.files[0]) {
      onFileSelect(event.dataTransfer.files[0]);
    }
  }, [onFileSelect, disabled]);

  const handleDragOver = useCallback((event: React.DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    event.stopPropagation();
    if (!disabled) setIsDragging(true);
  }, [disabled]);

  const handleDragLeave = useCallback((event: React.DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    event.stopPropagation();
    if (event.currentTarget.contains(event.relatedTarget as Node)) {
        return;
    }
    setIsDragging(false);
  }, []);

  return (
    <div className="w-full">
      <label
        htmlFor="file-upload"
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        className={`
          flex flex-col items-center justify-center w-full h-64 
          border-2 border-dashed rounded-xl cursor-pointer
          transition-colors duration-300 ease-in-out
          ${disabled ? 'bg-neutral-800 border-neutral-700 cursor-not-allowed opacity-70' : 
            isDragging ? 'bg-yellow-700/20 border-yellow-500' : 'bg-neutral-800/70 hover:bg-neutral-700/70 border-neutral-700 hover:border-yellow-600'
          }
        `}
        aria-disabled={disabled}
      >
        <div className="flex flex-col items-center justify-center pt-5 pb-6 text-center">
          <UploadIcon className={`w-10 h-10 mb-4 ${disabled ? 'text-neutral-500' : isDragging ? 'text-yellow-300' : 'text-yellow-500'}`} />
          <p className={`mb-2 text-base font-semibold ${disabled ? 'text-neutral-500' : isDragging ? 'text-yellow-200' : 'text-neutral-200'}`}>
            {isDragging ? 'Drop file here' : 'Click to upload or drag & drop'}
          </p>
          <p className={`text-xs mb-1 ${disabled ? 'text-neutral-600' : isDragging ? 'text-yellow-300' : 'text-neutral-400'}`}>
            Image (PNG, JPG, GIF) or Video (MP4, WEBM)
          </p>
          {!disabled && (
            <p className={`text-xs flex items-center ${isDragging ? 'text-yellow-400' : 'text-neutral-500'}`}>
              <DocumentDuplicateIcon className="w-3 h-3 mr-1" /> or paste image (Ctrl/Cmd+V)
            </p>
          )}
        </div>
        <input
          id="file-upload"
          type="file"
          className="hidden"
          accept="image/*,video/*"
          onChange={handleFileChange}
          disabled={disabled}
        />
      </label>
    </div>
  );
};

// src/lib/components/analysis/FileUpload.svelte
<script lang="ts">
  import { analysisStore } from '$lib/stores/analysis.svelte';
  import { formatFileSize, isValidMediaType } from '$lib/utils/fileUtils';
  import Button from '$lib/components/ui/Button.svelte';

  let isDragging = $state(false);
  let fileInputRef = $state<HTMLInputElement>();

  function handleDragOver(e: DragEvent) {
    e.preventDefault();
    isDragging = true;
  }

  function handleDragLeave() {
    isDragging = false;
  }

  function handleDrop(e: DragEvent) {
    e.preventDefault();
    isDragging = false;

    const files = e.dataTransfer?.files;
    if (files && files.length > 0) {
      handleFile(files[0]);
    }
  }

  function handleFileSelect(e: Event) {
    const input = e.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      handleFile(input.files[0]);
    }
  }

  function handleFile(file: File) {
    if (!isValidMediaType(file)) {
      analysisStore.error = 'Please upload a valid image or video file (JPEG, PNG, GIF, WebP, MP4, WebM)';
      return;
    }
    analysisStore.setFile(file);
  }

  function clearFile() {
    analysisStore.clearFile();
    if (fileInputRef) {
      fileInputRef.value = '';
    }
  }
</script>

<div class="space-y-4">
  {#if !analysisStore.uploadedFile}
    <!-- Drop Zone -->
    <div
      class="relative border-2 border-dashed rounded-xl p-8 text-center transition-all duration-200 cursor-pointer {isDragging ? 'border-accent bg-accent-light/50 scale-[1.01]' : 'border-gray-300 hover:border-accent hover:bg-accent-light/30'}"
      ondragover={handleDragOver}
      ondragleave={handleDragLeave}
      ondrop={handleDrop}
      onclick={() => fileInputRef?.click()}
      role="button"
      tabindex="0"
      onkeydown={(e) => e.key === 'Enter' && fileInputRef?.click()}
    >
      <input
        bind:this={fileInputRef}
        type="file"
        accept="image/*,video/*"
        class="hidden"
        onchange={handleFileSelect}
      />

      <div class="flex flex-col items-center gap-4">
        <div class="w-16 h-16 bg-accent-light rounded-full flex items-center justify-center">
          <svg class="w-8 h-8 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
          </svg>
        </div>
        <div>
          <p class="text-gray-900 font-medium">Drop your file here, or click to browse</p>
          <p class="text-sm text-gray-500 mt-1">Supports images (JPEG, PNG, GIF, WebP) and videos (MP4, WebM)</p>
        </div>
      </div>

      {#if isDragging}
        <div class="absolute inset-0 bg-accent/10 rounded-xl flex items-center justify-center pointer-events-none">
          <p class="text-accent font-medium">Drop to upload</p>
        </div>
      {/if}
    </div>
  {:else}
    <!-- File Preview -->
    <div class="bg-gray-50 rounded-xl p-4 border border-gray-200">
      <div class="flex items-start gap-4">
        <!-- Preview Thumbnail -->
        <div class="w-24 h-24 bg-gray-200 rounded-lg overflow-hidden flex-shrink-0">
          {#if analysisStore.isVideo}
            <video
              src={analysisStore.uploadedFilePreview}
              class="w-full h-full object-cover"
              muted
            ></video>
          {:else}
            <img
              src={analysisStore.uploadedFilePreview}
              alt="Preview"
              class="w-full h-full object-cover"
            />
          {/if}
        </div>

        <!-- File Info -->
        <div class="flex-1 min-w-0">
          <p class="font-medium text-gray-900 truncate">{analysisStore.uploadedFile.name}</p>
          <p class="text-sm text-gray-500 mt-1">
            {formatFileSize(analysisStore.uploadedFile.size)}
            <span class="mx-1.5">·</span>
            {analysisStore.isVideo ? 'Video' : 'Image'}
          </p>
          <div class="flex items-center gap-2 mt-3">
            <Button variant="ghost" size="sm" onclick={clearFile}>
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
              Remove
            </Button>
            <Button variant="ghost" size="sm" onclick={() => fileInputRef?.click()}>
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Replace
            </Button>
          </div>
        </div>
      </div>
    </div>

    <input
      bind:this={fileInputRef}
      type="file"
      accept="image/*,video/*"
      class="hidden"
      onchange={handleFileSelect}
    />
  {/if}
</div>
